version: 2

workflows:
  version: 2
  build:
    jobs:
      - macos_build
      - linux_build
  tag_build:
    jobs:
      - linux_build:
          filters:
            tags:
              only:
                - "/.*/"
            branches:
              ignore: /.*/

jobs:
  macos_build:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run:
          name: ddev install (macos)
          command: brew update && brew tap drud/ddev && brew install ddev
      - run: ddev version
  linux_build:
    machine:
      image: circleci/classic:201708-01
    steps:
      - checkout
      - run:
          name: curl ddev install
          command: curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash
      - run: ddev version


